// Regenerate src/stocks.data.ts from the official Nasdaq Trader symbol directory.
// This directory is the authoritative list of US-listed symbols (NASDAQ + NYSE +
// NYSE Arca/American), which is effectively the universe Gotrade trades: US
// common stocks, ADRs, and ETFs. We filter OUT instruments Gotrade does not list
// (warrants, units, rights, preferred shares, notes/bonds, test issues) so the
// picker only shows things you can actually buy there.
//
//   node scripts/gen-stocks.mjs
//
// Run again whenever you want to refresh the list (new listings/delistings).
import { writeFileSync } from "node:fs";

const SOURCES = [
  { url: "https://www.nasdaqtrader.com/dynamic/SymDir/nasdaqlisted.txt", other: false },
  { url: "https://www.nasdaqtrader.com/dynamic/SymDir/otherlisted.txt", other: true },
];

// Name fragments that mark instruments Gotrade does not list.
const EXCLUDE = /\b(warrant|right|unit|preferred|depositary.*preferred|notes?\b|debenture|subordinat|convertible note|when issued|when distributed|contingent value|partnership unit)\b/i;

function clean(name) {
  return name
    .replace(/\s*-?\s*(sponsored\s+)?(common stock|ordinary shares|class [a-z]|common shares|american depositary (shares|share|receipts?)|sponsored adr|adr|shares of beneficial interest|ETF|exchange traded fund|depositary shares|trust).*$/i, "")
    .replace(/\s+(Inc|Corp(oration)?|Co|Ltd|plc|S\.?A|N\.?V|Group|Holdings?|Limited|Company)\.?,?$/i, "")
    .replace(/\s+(Inc|Corp(oration)?|Co|Ltd|plc|S\.?A|N\.?V|Group|Holdings?|Limited|Company)\.?,?$/i, "")
    .replace(/,?\s+New$/i, "")
    .replace(/[,\s]+$/, "")
    .replace(/\s+/g, " ")
    .trim() || name.trim();
}

async function fetchRows(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${url} -> ${res.status}`);
  const text = await res.text();
  return text.split("\n").map((l) => l.trim()).filter(Boolean);
}

const seen = new Map(); // sym -> name (dedupe, first wins)

for (const { url, other } of SOURCES) {
  const rows = await fetchRows(url);
  for (const row of rows) {
    if (row.startsWith("Symbol|") || row.startsWith("ACT Symbol|") || row.startsWith("File Creation")) continue;
    const f = row.split("|");
    // nasdaqlisted: Symbol|Name|MktCat|TestIssue|FinStatus|RoundLot|ETF|NextShares
    // otherlisted:  ACTSym|Name|Exchange|CQS|ETF|RoundLot|TestIssue|NASDAQSym
    const sym = f[0];
    const name = f[1] ?? "";
    const testIssue = other ? f[6] : f[3];
    if (!sym || !name) continue;
    if (testIssue === "Y") continue;
    if (EXCLUDE.test(name)) continue;
    // Yahoo Finance uses "-" for share classes (BRK-B), the directory uses ".".
    // Skip anything with other punctuation (preferred/warrant tickers like ABC$A).
    if (/[^A-Z.]/.test(sym)) continue;
    const yhoo = sym.replace(/\./g, "-");
    if (!seen.has(yhoo)) seen.set(yhoo, clean(name));
  }
}

const list = [...seen.entries()]
  .sort((a, b) => a[0].localeCompare(b[0]))
  .map(([sym, name]) => ({ sym, name }));

const body = list.map((s) => `  { sym: ${JSON.stringify(s.sym)}, name: ${JSON.stringify(s.name)} },`).join("\n");
const out = `// AUTO-GENERATED by scripts/gen-stocks.mjs — do not edit by hand.
// US-listed stocks & ETFs from the Nasdaq Trader directory (the Gotrade universe:
// common stock, ADRs, ETFs; warrants/units/preferred/notes excluded).
// Regenerate: node scripts/gen-stocks.mjs
import type { Stock } from "./stocks";

export const ALL_STOCKS: Stock[] = [
${body}
];
`;

writeFileSync(new URL("../src/stocks.data.ts", import.meta.url), out);
console.log(`Wrote src/stocks.data.ts with ${list.length} symbols.`);
